name = "ak-website"
main = "index.js"
compatibility_date = "2025-02-14"
keep_vars = true

vars = { AEM_ORG = "edspioneers", AEM_SITE = "kp-hw" }

[env.dev]
vars = { AEM_ORG = "edspioneers", AEM_SITE = "kp-hw" }
